### ISSUE TITLE
arrays unexpectedly wrapping return values

### ISSUE THREAD

**Issue by wxgeorge** [winebarrel/ruby-jq#15]
This gem seems to deviate from the jq binary with regards to the return type of certain queries. Specifically, arrays are wrapping the return value in a number of situations.

Line 22 of spec/jq_spec.rb has

```
expect(JQ('"Zzz"').search('.')).to eq(['Zzz'])
```

But running the same query with the `jq` binary gives

```
echo '"Zzz"' | jq '.'
# "Zzz"
```

Why is the addition of the array the appropriate behaviour?

**Comment by wxgeorge** [comment]
(`jq` is an awesome tool, and I'm very happy this gem exists - 🙏 thank you @winebarrel! - and I'd very like to use it in my projects, I just can't make sense of this behaviour ...)

**Comment by voke** [comment]
I think you got a point. When no block is given to the `search()` method it should join all `str` and call `parse_json()` only once before returning. https://github.com/winebarrel/ruby-jq/blob/3796fb7c0ec02ba3067d2a3b83672ec013066e7c/lib/jq/parser.rb#L12-L41

**Comment by voke** [comment]
I guess it's because jq can produce **multiple outputs** and will print a newline after each output.

```
echo '["foo", "bar"]' | jq '.[] | ascii_upcase'
```
**Result:**
```
"FOO"
"BAR"
```
---------
```
JQ('["foo", "bar"]').search('.[] | ascii_upcase')
```
**Result:**
```
["FOO", "BAR"]
```
