### ISSUE TITLE
json key is symbol

### ISSUE THREAD

**Issue by wangmin19861205** [winebarrel/ruby-jq#3]
my json like this {:abc=>"123",:abb=>"123"},but use {}.jq('.')  
retune {"abc"=>"123".....}
so   how can keep zhe key is symbol

**Comment by tpickett66** [comment]
Sadly you can't, part of the round trip to JSON and back is the loss of this type information.

**Comment by johnallen3d** [comment]
You could consider using the [`oj`](https://github.com/ohler55/oj) gem which has a `symbol_keys` option. Because `ruby-jq` uses `multi_json` you should be able to just `gem 'oj'` in your `Gemfile` and then set:

```ruby
require 'oj'

Oj.default_options = { symbol_keys: true }
```
