### ISSUE TITLE
string output?

### ISSUE THREAD

**Issue by kswope** [winebarrel/ruby-jq#4]
I don't see anyway to have string output.

I'm interested in jq because of output formatting, especially --sort-keys.

I don't see this library allowing for the use of jq formatting, I'm just seeing the filtering side of jq.

**Comment by winebarrel** [comment]
You can sort the keys of JSON with the following code:

```ruby
require 'json'
json = '{"foor":100,"bar":100}'
json = Hash[JSON.parse(json).sort_by {|k, _| k }]
puts JSON.pretty_generate(json)
#=> {
#     "bar": 100,
#     "foor": 100
#   }
```
